streamer: tidesoftime

playing: hearthstone

streamerDir: /Users/Michaeliu/Twitch/streamer/tidesoftime

logDir: /Users/Michaeliu/Twitch/streamer/tidesoftime/log

keywords: # the words you want to highlight in the entire log  
  - hearthstone
  - deck
  - decklist
