streamer: reckful

playing: hearthstone

log_dir: /Users/Michaeliu/Twitch/streamer/reckful/log

keywords: # the words you want to highlight in the entire log  
  - hearthstone
  - deck
  - decklist
  - reckful
  - jew
  - bald
