streamer: reckful

playing: hearthstone

log_dir: /Users/Michaeliu/Twitch/streamer/reckful/log

num_topics: 20

keywords: # the words you want to highlight in the entire log  
  - hearthstone
  - reckful
  - jew
  - bald
